### PR TITLE
Settings Page

### PR DESCRIPTION
**Pull request by jiyingqi**
Added settings page functionality, you will need to run a lot of npm install for the package that was used for this. Let me know how you like it!

### CODE REVIEW

**Comment by jleckron** [comment]
Looks great!

**Comment by 50vincents** [comment]
looks good to me

**Comment by amizusawa** [comment]
On my phone the font size seems to be too big. The "Welcome to the Quiet Place" message extends beyond the borders of my screen. Is this an issue on my end?

**Comment by jiyingqi** [comment]
> On my phone the font size seems to be too big. The "Welcome to the Quiet Place" message extends beyond the borders of my screen. Is this an issue on my end?

This might be an issue with your phone? Do you have an IPhone?

**Pull request merged**
